### PR TITLE
Adding consistency of theme through pages

### PR DESCRIPTION
**Pull request by Eneshjakhar**
added the following:

+ updated login page css so it looks more appealing, and remains consistent through the application.
+ updated signup page css so it looks more appealing, and remains consistent through the application.
+ updated server page css so it looks more appealing, and remains consistent through the application.
+ added video call page(user to user) css styling so  it follows one theme, and remains consistent through the application.
+ added button for video call on the server page, therefore linking those pages. 
+ added nav bar on login page and signup page as well, now it's easier to navigate through them and go back to home page.

### CODE REVIEW

**Comment by Lunilux24** [comment]
Looks good. Have just one thing that I'd like you to fix. 

- Form boxes for login and signup need to be bigger.
- Need buttons to link to friend page

**Comment by Eneshjakhar** [comment]
buttons added and form boxes consistent.

**Comment by Eneshjakhar** [comment]
merge if looks good.

**Review by jordanp2002 — APPROVED** [review]
looks good

**Pull request merged**
