### PR TITLE
Account settings backend

### PR DESCRIPTION
**Pull request by ez4papiz1**
Added 2 files: back-end for account setting page AccountSettings.js and a user model file User.model.js

### CODE REVIEW

**Review by jordanp2002 — APPROVED** [review]

**Review by jordanp2002 — APPROVED** [review]

**Review by jordanp2002 — APPROVED** [review]
Looks good!

**Review by jordanp2002 — APPROVED** [review]
Looks good!

**Review by jordanp2002 — APPROVED** [review]
Looks good!

**Review by TrenchII — APPROVED** [review]
Looks generally good, need to change req.body.name to req.body.username in both files to match frontend

**Pull request merged**
